<!-- CSS here -->
<link rel="stylesheet" href="view/static/css/bootstrap.min.css">
<link rel="stylesheet" href="view/static/css/owl.carousel.min.css">
<link rel="stylesheet" href="view/static/css/magnific-popup.css">
<link rel="stylesheet" href="view/static/css/font-awesome.min.css">
<link rel="stylesheet" href="view/static/css/themify-icons.css">
<link rel="stylesheet" href="view/static/css/nice-select.css">
<link rel="stylesheet" href="view/static/css/flaticon.css">
<link rel="stylesheet" href="view/static/css/gijgo.css">
<link rel="stylesheet" href="view/static/css/animate.min.css">
<link rel="stylesheet" href="view/static/css/slick.css">
<link rel="stylesheet" href="view/static/css/slicknav.css">
<link rel="stylesheet" href="view/static/css/style.css">

